### ISSUE TITLE
support other bbox argument types

### ISSUE THREAD

**Issue by jonathancallahan** [MazamaScience/MazamaSatelliteUtils#19]
The `isDaylight()` function inside `utils_time.R` is useful for determining which files are worth downloading and working with. It uses NOAA "ephemerides" calculations to provide precise sunrise and sunset information for any combination of date and location.

This function currently handles a `bbox` as created with the `sp::bbox()` function:

```
library(MazamaSpatialUtils)
mx <- subset(SimpleCountries, countryCode == "MX")
bbox <- bbox(mx)
print(bbox)
```

This function should also handle a bbox as created by `raster::extent()`:

```
library(MazamaSatelliteUtils)
G16_filepath <- system.file(
  "extdata", 
  "OR_ABI-L2-AODC-M6_G16_s20192491826095_e20192491828468_c20192491835127.nc", 
  package = "MazamaSatelliteUtils")
nc <- ncdf4::nc_open(G16_filepath)
raster <- goesaodc_createRaster(nc, res = 0.1, dqfLevel = 2)
extent <- raster::extent(raster)
print(extent)
```

We can test for this with `class(extent) == "Extent"` and `typeof(extent) = "S4"`.

Other functions that accept the `box` argument can be found with `grep "@param bbox" R/*`. At least one, `goesaodc_createSpatialPoints()` needs the box edges.

**I haven't totally thought this through and leave it up to your judgement. --** It may make sense to have a general `utils.R` file with a `bboxToVector()` function which accepts any of the above formats and returns a vector of floats in `c(lonLo, lonLo, latLo, latHi)` order.

 - [x] add support for `bbox` of type "Extent"
 - [x] add support for `bbox` of type `is.numeric() && is.vector()` in W, E, S, N order (or make good case why the ordering should be otherwise)
 - [x] add detailed documentation for the capabilities of this function
 - [x] add this functionality to any other functions where bbox information is used rather than just passed through

**Comment by lagerratrobe** [comment]
Looks like all of the following files have an @param bbox

goesaodc_createDaytimeRasterStack.R
goesaodc_createHourlyRasterStack.R
goesaodc_createRaster.R
goesaodc_createSpatialPoints.R
raster_createLocationTimeseries.R
~~utils-time.R~~

**Comment by lagerratrobe** [comment]
Wrote new bboxToVector() function in a new utils.R file as proposed above.
