### ISSUE TITLE
add ncdf data example

### ISSUE THREAD

**Issue by jonathancallahan** [MazamaScience/MazamaSatelliteUtils#23]
We should add example netcdf files to the `data/` directory and create package documentation for it. Data will be documented in `MazamaSatelliteUtils.R.  Examples can be seen here:

https://github.com/MazamaScience/AirSensor/blob/master/R/AirSensor.R

I would recommend using a single time slice from the camp fire during the middle of the day. You should pick a time that has some reasonable amount of data over California. We will want one file from GOES 16 (East) and one from Goes 17 (West).

Relevant documentation for adding data to packages is here: http://r-pkgs.had.co.nz/data.html

Not sure if there are any issues storing non-RData binary files.

**Comment by lagerratrobe** [comment]
Want to use the data from GOES 17 for Sep 3, 2019 that captures the Walker Fire in the Plumas National Forest in California.  Reasonable BBOX coords for this are: 
LL = -122.76, 39.19
UR = -116.78, 43.54

**Comment by lagerratrobe** [comment]
One issue that we may have problems with is the file size of these .nc files, which is slightly larger than 3 Mb each.  From the CRAN package data page:

_CRAN notes
Generally, package data should be smaller than a megabyte - if it’s larger you’ll need to argue for an exemption. This is usually easier to do if the data is in its own package and won’t be updated frequently. You should also make sure that the data has been optimally compressed:__

**Comment by lagerratrobe** [comment]
Checked in 2 NetCDF files into MazamaSatelliteUtils /data dir.  Also added a data.R file in /R dir, per instructions in http://r-pkgs.had.co.nz/data.html
