### ISSUE TITLE
flesh out documentation for existing functions

### ISSUE THREAD

**Issue by jonathancallahan** [MazamaScience/MazamaSatelliteUtils#24]
The roxygen2 documentation in each function can be improved.

Each `goesaodc_~()` function should have a working example using the netcdf files that were added to the package. A person should be able to read the documentation for a function, have a pretty good idea of how it fits into the overall framework and then be able to run the examples at the R console.

Some examples should only use package data while others may require data found in the `satelliteDataDir`. In this latter case, examples can be encased in `\dontest{}`. This will allow us to test these examples if we want (using the `R CMD check --run-donttest` option).

Function documentation should be fleshed out with a paragraph length description in some cases. 

 - [x] R/goesaodc_createDaytimeRasterStack.R
 - [x] R/goesaodc_createHourlyRasterStack.R
 - [x] R/goesaodc_createRaster.R
 - [x] R/goesaodc_createSpatialPoints.R
 - [x] R/goesaodc_createTibble.R
 - [x] R/goesaodc_downloadAOD.R
 - [x] R/goesaodc_listFiles.R
 - [x] R/goesaodc_openFile.R
 - [x] R/goesaodc_plotSpatialPoints.R
 - [x] R/installGoesGrids.R
 - [ ] make sure everything works with `R CMD check`

**Comment by lagerratrobe** [comment]
I think these are looking pretty good.  Might be worth doing another pass when we are ready to release.
