### ISSUE TITLE
Working with GOES AODC Rasters vignette

### ISSUE THREAD

**Issue by jonathancallahan** [MazamaScience/MazamaSatelliteUtils#26]
A second vignette should focus on working with the raster and rasterVis packages.

It might be worth creating a rasterStack for an hour's worth of Northern California during the camp fire. We can describe how it was created in the vignette with code that isn't run and the continue working with the pre-generated, package raster stack.

This vignette should cover:

1) Understanding raster objects
2) Creating the raster grid
3) "Rasterizing" SpatialPoints onto the grid
4) Assessing the quality of the rasterLayer by looking at different metrics -- count, sd, etc.
5) Creating a raster stack and using it to average
6) Basic rasterVis plotting

**Comment by lagerratrobe** [comment]
This appears to exist already in "working_with_goes_aodc_rasters".  Might need to change colors or geographic extents to make it look better, but otherwise it seems to meet the requirements of this issue.
