### ISSUE TITLE
Data Quality vignette

### ISSUE THREAD

**Issue by jonathancallahan** [MazamaScience/MazamaSatelliteUtils#27]
We should have a third vignette that dives into data quality and covers:

1) Understanding the DQF parameter
2) Example plots colored by DQF
3) Assessing the quality of rasterization with count, sd, etc.
4) Best practices for using QC in the process of creating hourly averages

**Comment by lagerratrobe** [comment]
This material is covered in several of the vignettes that Tate wrote already.
