### ISSUE TITLE
functions to generate GOES grids

### ISSUE THREAD

**Issue by jonathancallahan** [MazamaScience/MazamaSatelliteUtils#38]
The GOES grids currently in the `data/` directory are way too big to be released as part of the package:

```
$ du -sh data/*
 49M	data/goesEastGrid.rda
 48M	data/goesWestGrid.rda
```

We should have a function to generate these and save them in `satelliteDataDir` as part of a user's initial setup of the package.

 - [x] merge the `master` branch changes to get `installGoesGrids.R`
 - [x] flesh out the documentation in `installGoesGrids.R`
 - [x] add `showProgress` capability using the `progress` package as described in the `ROGER:` comments. You will need to include this package in the `DESCRIPTION`.
 - [x] remove `goesEastGrid.rda` and `goesWestGrid.rda` from the `data/` directory 
 - [x] follow `ROGER:` instructions in `goesaodc_createTibble.R` to load GOES grid data from `satelliteDataDir`
 - [x] follow `ROGER:` instructions in `goesaodc_createTibble.R` to create an example that can be run on our desktop machines
 - [x] modify `goes_createRaster.R` using code very similar or identical to that in `goesaodc_createTibble.R` to load GOES grid data from `satelliteDataDir`
 - [x] update the example in `goesaodc_createRaster.R` to run as `\donttest{}` with one of the package internal netcdf files
 - [x] refactor the `goesaodc_isGoesProjection()` function in `R/utils_goesaodc.R` to reference the grid files in `satelliteDataDir`
 - [x] make sure the package passes `R CMD check` (_i.e._ the "Check" button)

**Comment by tabrasel** [comment]
My code to generate the `goesWestGrid` is located in the `local_scratch/tate-createGoesWestGrid` script if that's useful!

**Comment by lagerratrobe** [comment]
Pulled this out as I completed the tasks.
```  
  # ROGER:  The goestEastGrid and goestWestGrid are no longer available as
  #         package variables. We will need to:
  # [X] ROGER:    1) have satID choose which data file to load
  # [X] ROGER:    2) test for existence and stop with an appropriate message 
  #                  if not found
  # [X] ROGER:    3) load them into memory with something like:
  #   gridFile <- "goestEastGrid.rda"
  #   filePath <- file.path(getSatelliteDataDir(), gridFile)
  #   goesGrid <- get(load(filePath))
  # [X] ROGER:  4) obtain lon and lat from the now in-memory goesGrid
```

**Comment by lagerratrobe** [comment]
```
# ROGER:  Read up on \dontrun{} amd \donttest{} at:
# ROGER:    https://kbroman.org/pkg_primer/pages/tests.html
# ROGER:    https://cran.r-project.org/web/packages/roxygen2/vignettes/rd.html
# ROGER:
# ROGER:  Also spend some time understanding the use of devtools::test()
# ROGER:
# ROGER:  Update the example below to be \donttest{} and to use one of the
# ROGER:  package internal netcdf files. This should run fast on our desktop
# ROGER:  machines where the goesGrid files have already been created.
```
Ok, but there is a problem with this.  We can't use _goesaodc_openFile()_ because it automatically assumes a path that is under _SatelliteDataDir_.  The example I made works, but calls ncdf4::nc_open directly.

**Comment by lagerratrobe** [comment]
```
  # ROGER:  Optional "showProgress = TRUE"
) {
  
  # ROGER:  Can we use the progress package to display a progress bar??
  # ROGER:    https://github.com/r-lib/progress
  # ROGER:
  # ROGER:  The goal is only to let someone know that work is being done and
  # ROGER:  show elapsed time.
  ```
Can't do it.  Can't figure out how to make this work with the _getCoordGrid()_, which is the function that's expensive.  Talked it over with Jon and we're going to just print out a message to the console as we build the grids.

**Comment by lagerratrobe** [comment]
Working on the last part of Jon's checklist, "make sure that CMD CHECK passes".  I think in order to do that, I need to do the following:

- [] Check that all examples in R files contain code that can be executed locally
- [] make sure that all examples are set to \donttest, except for installGoesGrid() which should be \dontrun

**Comment by lagerratrobe** [comment]
Running all examples in .R files.
- [ ] goesaodc_createDaytimeRasterStack.R
goesaodc_createHourlyRasterStack.R
goesaodc_createRaster.R
goesaodc_createSpatialPoints.R
goesaodc_createTibble.R
goesaodc_downloadAOD.R
goesaodc_listFiles.R
goesaodc_openFile.R
goesaodc_plotSpatialPoints.R
installGoesGrids.R
maiac_2nc4.R
maiac_cropRaw.R
maiac_downloadNorthAmerica.R
maiac_getMetadata.R
maiac_loadRaster.R
maiac_loadRawDataframe.R
maiac_pm25ToAod.R
MazamaSatelliteUtils.R
raster_createLocationTimeseries.R
raster_createStackAverage.R
utils-goesaodc.R
utils-nc.R
utils-pipe.R
utils-raster.R
utils-time.R
