### ISSUE TITLE
try moving vignettes back into the package

### ISSUE THREAD

**Issue by jonathancallahan** [MazamaScience/MazamaSatelliteUtils#40]
In order to get the package to pass `R CMD check` without referencing data on my desktop machine, I moved the existing vignettes to `local_vignettes/`.

We would like to have updated versions of these in the `vignettes/` directory where they will become part of the package documentation. But the vignettes currently reference lots of things that either: 1) take a long time to compute or 2) reference files in "non-package" locations. So the task is to figure out what we need to do to get some version of the existing `local_vignettes/` back into the package in a way that passes `R CMD check`

This task is *experimental* in nature in that I don't know ahead of time the proper way to proceed. It will involve some reading up on package structure, vignettes building, _etc._.

 - [x] intro_do_goes_aodc_data.Rmd
 - [x] working_with_goes_aodc_rasters.Rmd
 - [x] grid_sizes.Rmd
 - [x] goes-east_data_quality_limits.Rmd

One possibility for vignettes that take a very long time to create is to put them in a subdirectory of `vignettes/`. I believe this will prevent them from being processed by `R CMD check` but will still allow them to part of the documentation generated by `pkgdown::build_site()`.

**Comment by lagerratrobe** [comment]
Updated all of the vignette code to make it work with changes since Aug 2019 and moved them back into a "vignettes" directory.  Package builds and vignettes are generated.
