### ISSUE TITLE
Update the .nc files to be smaller and more useful

### ISSUE THREAD

**Issue by lagerratrobe** [MazamaScience/MazamaSatelliteUtils#51]
Currently we only have 2 large .nc files in extdata which are used to both generate the GoesEast and GoesWest grids, as well as populate some of the examples in the package.  However, because these only represent a single 5-min snapshot of data, there is no way to use them to create examples with time-series.

It would be more useful if we could create and store cropped .nc files which cover a smaller area of interest and a period of at least one day.

Investigate whether we can crop the larger .nc files into smaller peices and use those pieces with the rest of the existing workflow and tools.

**Comment by jonathancallahan** [comment]
As a first step, we should address two `R CMD check` issues at once with the following steps:

- [ ] Figure out how to generate the `~Grid.rda` files algorithmically (#50).
- [ ] Find G16/G17 examples with good coverage over a smaller region. Possible regions include: 4 corners states; CA-NV, norther CA, Sonoma county. Goal is to have .nc files smaller < 0.5 MB.
- [ ] Rename the files to, _e.g._ `OR_ABI-L2-AODC-M6_G17_s20192491826196_e-_c-.nc`
- [ ] Update all the examples and tests to use the new files.
