### ISSUE TITLE
Make it easy to color by 10^AOD 

### ISSUE THREAD

**Issue by jonathancallahan** [MazamaScience/MazamaSatelliteUtils#53]
The value of AOD we read in from the data files is related to the concept of "mass attenuation coefficient" or "mass extinction coefficient". As such, we *believe* it has a log relationship to the actually mass density. Our initial attempts to create color scales based on `10^AOD` made for plots that were immediately interpretable as smoke plumes.

Not sure whether we need a utility function to deal with this or just improved examples. But we should probably only be displaying plots with color scales based on `10^AOD`.

**Comment by lagerratrobe** [comment]
Moot point now that we've figured out we're not getting the full or proper range of AOD values from the files. See issue #72.  Closing this as "won't fix".
