### ISSUE TITLE
find a better date/hour for examples

### ISSUE THREAD

**Issue by jonathancallahan** [MazamaScience/MazamaSatelliteUtils#54]
All of our examples right now use an image that leaves a first impression of: "Satellite data is messed up!". This is not what we want. 

We need to spend some time finding a dataset for the examples. This dataset should produce maps that look more like what you might expect with some obvious features like river valleys or smoke plumes that make sense to the naked eye.

One tool that can help with quick and easy viewing of datasets is Panoply https://www.giss.nasa.gov/tools/panoply/download/

**Comment by lagerratrobe** [comment]
The plot that you created from October 27, 2019 of the area south of the Kincade fire looks pretty good.  Pertinent details are:

Date: "2019-10-27 14:00:00 UTC"
Location:   bbox <- c(-124, -120, 36, 39)

Will update all examples to work with this area and date.  Will probably wait until we've solidified how we want to materialize bbox-filtered data locally.  Probably as nativeGrids.

**Comment by lagerratrobe** [comment]
I've updated and run all of the examples in the package that display any type of plot, except for 2 that were already showing good data at the Milepost 97 fire.  Everything else points to the Kincade Fire on Oct 27.
