### ISSUE TITLE
change `julian` argument to `isJulian` throughout

### ISSUE THREAD

**Issue by jonathancallahan** [MazamaScience/MazamaSatelliteUtils#56]
It turns out there is a `base::julian()` function. Just to avoid confusion and to communicate that this argument accepts a logical, it should be changed to `isJulian`.

(In case you don't already know, SublimeText is a wonderful tool for global find-and-replace.)

**Comment by lagerratrobe** [comment]
```
$ grep -l "@param julian" *.R | grep -v maiac
getDaylightHours.R
goesaodc_createRasterStack.R
goesaodc_downloadAOD.R
goesaodc_downloadDaytimeAOD.R
goesaodc_listDaytimeFiles.R
goesaodc_listFiles.R
```

Updated files above and added tests for isJulian param.
