### ISSUE TITLE
Create new examples of functionality

### ISSUE THREAD

**Issue by lagerratrobe** [MazamaScience/MazamaSatelliteUtils#59]
- [ ] Create an example that average an hours worth of data on the native grid (without rasterizing). That way we can generate plots that have more of the grid cells filled in as long as we use mean(..., na.rm = TRUE).

- [ ] Create a quick-and-dirty script in local_R/ showing how to create one or more pictures or maps of what can be seen for this important wildfire [Kincade, Sonoma]. Go ahead and upgrade it to an Rmarkdown document if you want. We should probably have a local_Rmd/ for nice examples.

- [ ] Create an example that uses data from the Noon hour across a span of many days.  Rasterize and average the data across the hour for each day.  See if the points in the tibble line up, or whether a raster is required for pixel averaging.  Map the data and show points of interest and contextual GIS data.

**Comment by jonathancallahan** [comment]
These examples should wait for the ability to pass a `bbox` argument to `goesaodc_createTibble()`.

**Comment by jonathancallahan** [comment]
I have moved my example scripts to a new `local_jon/` directory.
