### ISSUE TITLE
add bbox support to goesaodc_createTibble

### ISSUE THREAD

**Issue by jonathancallahan** [MazamaScience/MazamaSatelliteUtils#62]
Most satellite data use cases for the USFS AirFire group involve looking at a region of interest -- typically the size of a state or smaller.

We can make everything work faster and use much less memory if we only ingest data within the area of interest. To do this, the `goesaodc_createTibble()` function needs to support a `bbox` argument. The function signature should look like this:

```
goesaodc_createTibbl <- function(
  nc = NULL,
  bbox = NULL
) {
  ...
}
```

Prototype code demonstrating how to convert a bbox into curvilinear coordinate bounding indices and then ingest only the data within those bounding indices is found on the `jon` branch in `local_jon/Kincade-20191027-example.R`.

**Comment by lagerratrobe** [comment]
Done.
