### ISSUE TITLE
enhance createSpatialPointsVideo_exec.R

### ISSUE THREAD

**Issue by jonathancallahan** [MazamaScience/MazamaSatelliteUtils#70]
In an effort to help USFS (and NASA) personnel understand how useful GOES AOD _might_ be, they first need to see where it is available and what it shows. To satisfy this, we will make it easy to create short videos over areas of interest.

A first example script for creating videos is see in `local_executables/createSpatialPointsVideo_exec.R`. Several features to understand about this script:

* It is an `_exec` script that is to be run from the Unix command line.
* It begins with `#!/usr/local/bin/Rscript` and must be made executable before running it from the command line.
* It is designed so that it can also be run directly from RStudio by just sourcing it or by highlighting and running a chunk at a time for development and debugging.
* It has lots of arguments so that it can be run in automated fashion with a cron job that will run the code in a purpose-built docker container.

The current version of this script only works with an hours worth of data and only allows for specification of a state of interest. The first few tasks with this code are all marked with `TODO:` in the code. They should be approached in the following order:

- [x] familiarize yourself with the code and packages used (_e.g._ **optparse**)
- [x] make sure you have **ffmpeg** installed and can use it from the command line
- [x] obtain a timezone from the center of the `bbox` (Find the center and use `MazamaCoreUtils::getTimezone()`)
- [x] add support for a `bbox` argument as a string: "w,e,s,n"
- [x] support full days if the local timezone hour is midnight (be careful to only use daylight hours)
- [x] add `spatialDataDir` and `satelliteDataDir` command line arguments
- [x] use `goesaodc_areaPlot()` when it becomes available

**Comment by lagerratrobe** [comment]
I implemented the features you requested above.  I was a little unsure about the "fullDay" implementation you asked for, since we already had high-level functions that download and list teh files we need for a correct daylight timespan.  I used those and added a "fullDay" command-line option to control the behaviour.

Everything seems to work well and watching the movie for an entire day is rather fun.  Full-day movies and up being around 3.6 Mb for the bbox that I used.

**Comment by lagerratrobe** [comment]
Per our conversation, see about making the plot sizes uniform and styled in such a way that they look good, regardless of the extent passed in.  Also see if it makes sense to use goesaodc_areaPlot() instead of making the calls to createSpatialPoints()
